-------------------------------------------------------------------------------
-- File: PkgDPhyIfcRegmap.vhd
-- Author: Autogenerated by XmlParse
-- Original Project: --
-- Date: --
-------------------------------------------------------------------------------
-- (c) 2023 National Instruments Corporation. All Rights Reserved.
-------------------------------------------------------------------------------
-- Purpose:
--   The constants in this file are autogenerated by XmlParse.
-------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;
library work;
  use work.PkgXReg.all;
  --synopsys translate_off
  use work.PkgNiSim.all;
  --synopsys translate_on

package PkgDPhyIfcRegmap is

--===============================================================================
-- A numerically ordered list of registers and their HDL source files
--===============================================================================

  -- ChanEnableReg         : 0x0 (mipi_csi2_core_raw_stripped.xml)
  -- HsModeCtrlReg         : 0x4 (mipi_csi2_core_raw_stripped.xml)
  -- StopModeCtrlReg       : 0x8 (mipi_csi2_core_raw_stripped.xml)
  -- ChanStatus1Reg        : 0xC (mipi_csi2_core_raw_stripped.xml)
  -- ChanStatus2Reg        : 0x10 (mipi_csi2_core_raw_stripped.xml)
  -- PhyIfcSignatureReg    : 0x14 (mipi_csi2_core_raw_stripped.xml)
  -- PacketHeaderForGenReg : 0x18 (mipi_csi2_core_raw_stripped.xml)
  -- PacketFillerForGenReg : 0x1C (mipi_csi2_core_raw_stripped.xml)
  -- GenPacketReg          : 0x20 (mipi_csi2_core_raw_stripped.xml)
  -- TxChan0DebugReg0      : 0x24 (mipi_csi2_core_raw_stripped.xml)
  -- TxChan0DebugReg1      : 0x28 (mipi_csi2_core_raw_stripped.xml)
  -- TxStopStateDwellReg   : 0x2C (mipi_csi2_core_raw_stripped.xml)
  -- TxHighSpeedDwellReg   : 0x30 (mipi_csi2_core_raw_stripped.xml)
  -- ActiveLaneCount       : 0x34 (mipi_csi2_core_raw_stripped.xml)

--===============================================================================
-- RegTypes
--===============================================================================

--===============================================================================
-- Register Group Debug
--===============================================================================

  -- PacketHeaderForGenReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kPacketHeaderForGenReg : integer := 16#18#; -- Register Offset
  constant kPacketHeaderForGenRegSize: integer := 32;  -- register width in bits
  constant kPacketHeaderForGenRegMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kHeaderDataTypeSize       : integer := 6;  --PacketHeaderForGenReg:HeaderDataType
  constant kHeaderDataTypeMsb        : integer := 5;  --PacketHeaderForGenReg:HeaderDataType
  constant kHeaderDataType           : integer := 0;  --PacketHeaderForGenReg:HeaderDataType
  constant kHeaderVC10Size       : integer := 2;  --PacketHeaderForGenReg:HeaderVC10
  constant kHeaderVC10Msb        : integer := 7;  --PacketHeaderForGenReg:HeaderVC10
  constant kHeaderVC10           : integer := 6;  --PacketHeaderForGenReg:HeaderVC10
  constant kHeaderDataSize       : integer := 16;  --PacketHeaderForGenReg:HeaderData
  constant kHeaderDataMsb        : integer := 23;  --PacketHeaderForGenReg:HeaderData
  constant kHeaderData           : integer :=  8;  --PacketHeaderForGenReg:HeaderData
  constant kHeaderECCSize       : integer :=  6;  --PacketHeaderForGenReg:HeaderECC
  constant kHeaderECCMsb        : integer := 29;  --PacketHeaderForGenReg:HeaderECC
  constant kHeaderECC           : integer := 24;  --PacketHeaderForGenReg:HeaderECC
  constant kHeaderVC32Size       : integer :=  2;  --PacketHeaderForGenReg:HeaderVC32
  constant kHeaderVC32Msb        : integer := 31;  --PacketHeaderForGenReg:HeaderVC32
  constant kHeaderVC32           : integer := 30;  --PacketHeaderForGenReg:HeaderVC32
  function kPacketHeaderForGenRegRec return XReg2_t; -- Register Record function

  -- PacketFillerForGenReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kPacketFillerForGenReg : integer := 16#1C#; -- Register Offset
  constant kPacketFillerForGenRegSize: integer := 32;  -- register width in bits
  constant kPacketFillerForGenRegMask : std_logic_vector(31 downto 0) := X"000000ff";
  constant kFillerCountSize       : integer := 8;  --PacketFillerForGenReg:FillerCount
  constant kFillerCountMsb        : integer := 7;  --PacketFillerForGenReg:FillerCount
  constant kFillerCount           : integer := 0;  --PacketFillerForGenReg:FillerCount
  function kPacketFillerForGenRegRec return XReg2_t; -- Register Record function

  -- GenPacketReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kGenPacketReg : integer := 16#20#; -- Register Offset
  constant kGenPacketRegSize: integer := 32;  -- register width in bits
  constant kGenPacketRegMask : std_logic_vector(31 downto 0) := X"000000ff";
  constant kGenerateSize       : integer := 8;  --GenPacketReg:Generate
  constant kGenerateMsb        : integer := 7;  --GenPacketReg:Generate
  constant kGenerate           : integer := 0;  --GenPacketReg:Generate
  constant kGeneratingSize       : integer := 8;  --GenPacketReg:Generating
  constant kGeneratingMsb        : integer := 7;  --GenPacketReg:Generating
  constant kGenerating           : integer := 0;  --GenPacketReg:Generating
  function kGenPacketRegRec return XReg2_t; -- Register Record function

  -- TxChan0DebugReg0 Register (from mipi_csi2_core_raw_stripped.xml)
  constant kTxChan0DebugReg0 : integer := 16#24#; -- Register Offset
  constant kTxChan0DebugReg0Size: integer := 32;  -- register width in bits
  constant kTxChan0DebugReg0Mask : std_logic_vector(31 downto 0) := X"ffdffcff";
  constant kTxFifoEmptyCountSize       : integer := 8;  --TxChan0DebugReg0:TxFifoEmptyCount
  constant kTxFifoEmptyCountMsb        : integer := 7;  --TxChan0DebugReg0:TxFifoEmptyCount
  constant kTxFifoEmptyCount           : integer := 0;  --TxChan0DebugReg0:TxFifoEmptyCount
  constant kTxFifoFullCountSize       : integer :=  6;  --TxChan0DebugReg0:TxFifoFullCount
  constant kTxFifoFullCountMsb        : integer := 15;  --TxChan0DebugReg0:TxFifoFullCount
  constant kTxFifoFullCount           : integer := 10;  --TxChan0DebugReg0:TxFifoFullCount
  constant kTxDlStateSize       : integer :=  5;  --TxChan0DebugReg0:TxDlState
  constant kTxDlStateMsb        : integer := 20;  --TxChan0DebugReg0:TxDlState
  constant kTxDlState           : integer := 16;  --TxChan0DebugReg0:TxDlState
  constant kTxClHighSpeedSize       : integer :=  1;  --TxChan0DebugReg0:TxClHighSpeed
  constant kTxClHighSpeedMsb        : integer := 22;  --TxChan0DebugReg0:TxClHighSpeed
  constant kTxClHighSpeed           : integer := 22;  --TxChan0DebugReg0:TxClHighSpeed
  constant kTxFifoEmptyCount8Size       : integer :=  1;  --TxChan0DebugReg0:TxFifoEmptyCount8
  constant kTxFifoEmptyCount8Msb        : integer := 23;  --TxChan0DebugReg0:TxFifoEmptyCount8
  constant kTxFifoEmptyCount8           : integer := 23;  --TxChan0DebugReg0:TxFifoEmptyCount8
  constant kTxLaneHasSpaceSize       : integer :=  4;  --TxChan0DebugReg0:TxLaneHasSpace
  constant kTxLaneHasSpaceMsb        : integer := 27;  --TxChan0DebugReg0:TxLaneHasSpace
  constant kTxLaneHasSpace           : integer := 24;  --TxChan0DebugReg0:TxLaneHasSpace
  constant kTxLaneHasDataSize       : integer :=  4;  --TxChan0DebugReg0:TxLaneHasData
  constant kTxLaneHasDataMsb        : integer := 31;  --TxChan0DebugReg0:TxLaneHasData
  constant kTxLaneHasData           : integer := 28;  --TxChan0DebugReg0:TxLaneHasData
  function kTxChan0DebugReg0Rec return XReg2_t; -- Register Record function

  -- TxChan0DebugReg1 Register (from mipi_csi2_core_raw_stripped.xml)
  constant kTxChan0DebugReg1 : integer := 16#28#; -- Register Offset
  constant kTxChan0DebugReg1Size: integer := 32;  -- register width in bits
  constant kTxChan0DebugReg1Mask : std_logic_vector(31 downto 0) := X"ffff3fff";
  constant kTxPacketCountSize       : integer := 14;  --TxChan0DebugReg1:TxPacketCount
  constant kTxPacketCountMsb        : integer := 13;  --TxChan0DebugReg1:TxPacketCount
  constant kTxPacketCount           : integer :=  0;  --TxChan0DebugReg1:TxPacketCount
  constant kTxWordCountSize       : integer := 16;  --TxChan0DebugReg1:TxWordCount
  constant kTxWordCountMsb        : integer := 31;  --TxChan0DebugReg1:TxWordCount
  constant kTxWordCount           : integer := 16;  --TxChan0DebugReg1:TxWordCount
  function kTxChan0DebugReg1Rec return XReg2_t; -- Register Record function

--===============================================================================
-- Register Group Misc
--===============================================================================

  -- Enumerated type AxiStreamTUser
  constant kAxiStreamTUserSize : integer := 26;
  constant kSync                     : integer := 0;  -- AxiStreamTUser:Sync
  constant kSyncWarning              : integer := 1;  -- AxiStreamTUser:SyncWarning
  constant kSyncError                : integer := 2;  -- AxiStreamTUser:SyncError
  constant kInternalError            : integer := 3;  -- AxiStreamTUser:InternalError
  constant kHeader                   : integer := 4;  -- AxiStreamTUser:Header
  constant kHeaderNoError            : integer := 5;  -- AxiStreamTUser:HeaderNoError
  constant kHeaderCorrectedError     : integer := 6;  -- AxiStreamTUser:HeaderCorrectedError
  constant kHeaderUncorrectableError : integer := 7;  -- AxiStreamTUser:HeaderUncorrectableError
  constant kShortPacket              : integer := 8;  -- AxiStreamTUser:ShortPacket
  constant kLongPacketHeader         : integer := 9;  -- AxiStreamTUser:LongPacketHeader
  constant kEoT                      : integer := 10;  -- AxiStreamTUser:EoT
  constant kGoodCRC                  : integer := 11;  -- AxiStreamTUser:GoodCRC
  constant kBadCRC                   : integer := 12;  -- AxiStreamTUser:BadCRC
  constant kPayloadValidsLsb         : integer := 16;  -- AxiStreamTUser:PayloadValidsLsb
  constant kPayloadValidsMsb         : integer := 19;  -- AxiStreamTUser:PayloadValidsMsb
  constant kChecksumValidsLsb        : integer := 20;  -- AxiStreamTUser:ChecksumValidsLsb
  constant kChecksumValidsMsb        : integer := 23;  -- AxiStreamTUser:ChecksumValidsMsb
  constant kFillerValidsLsb          : integer := 24;  -- AxiStreamTUser:FillerValidsLsb
  constant kFillerValidsMsb          : integer := 27;  -- AxiStreamTUser:FillerValidsMsb
  constant kTruncatedPacketError     : integer := 28;  -- AxiStreamTUser:TruncatedPacketError
  constant kUpperPayloadValidsLsb    : integer := 29;  -- AxiStreamTUser:UpperPayloadValidsLsb
  constant kUpperPayloadValidsMsb    : integer := 32;  -- AxiStreamTUser:UpperPayloadValidsMsb
  constant kUpperChecksumValidsLsb   : integer := 33;  -- AxiStreamTUser:UpperChecksumValidsLsb
  constant kUpperChecksumValidsMsb   : integer := 36;  -- AxiStreamTUser:UpperChecksumValidsMsb
  constant kUpperFillerValidsLsb     : integer := 37;  -- AxiStreamTUser:UpperFillerValidsLsb
  constant kUpperFillerValidsMsb     : integer := 40;  -- AxiStreamTUser:UpperFillerValidsMsb

  -- Enumerated type ChannelBitMasks
  constant kChannelBitMasksSize : integer := 6;
  constant kNI148x01OutputChanBitMask : integer := 0;  -- ChannelBitMasks:NI148x01OutputChanBitMask
  constant kNI148x02InputChanBitMask  : integer := 0;  -- ChannelBitMasks:NI148x02InputChanBitMask
  constant kNI148x03OutputChanBitMask : integer := 16#33#;  -- ChannelBitMasks:NI148x03OutputChanBitMask
  constant kNI148x03InputChanBitMask  : integer := 16#cc#;  -- ChannelBitMasks:NI148x03InputChanBitMask
  constant kNI148x01InputChanBitMask  : integer := 16#ff#;  -- ChannelBitMasks:NI148x01InputChanBitMask
  constant kNI148x02OutputChanBitMask : integer := 16#ff#;  -- ChannelBitMasks:NI148x02OutputChanBitMask

  -- ChanEnableReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kChanEnableReg : integer := 16#0#; -- Register Offset
  constant kChanEnableRegSize: integer := 32;  -- register width in bits
  constant kChanEnableRegMask : std_logic_vector(31 downto 0) := X"c000ffff";
  constant kChanEnableSize       : integer := 8;  --ChanEnableReg:ChanEnable
  constant kChanEnableMsb        : integer := 7;  --ChanEnableReg:ChanEnable
  constant kChanEnable           : integer := 0;  --ChanEnableReg:ChanEnable
  constant kChanEnabledSize       : integer := 8;  --ChanEnableReg:ChanEnabled
  constant kChanEnabledMsb        : integer := 7;  --ChanEnableReg:ChanEnabled
  constant kChanEnabled           : integer := 0;  --ChanEnableReg:ChanEnabled
  constant kChanDisableSize       : integer :=  8;  --ChanEnableReg:ChanDisable
  constant kChanDisableMsb        : integer := 15;  --ChanEnableReg:ChanDisable
  constant kChanDisable           : integer :=  8;  --ChanEnableReg:ChanDisable
  constant kSetPhyResetSize       : integer :=  1;  --ChanEnableReg:SetPhyReset
  constant kSetPhyResetMsb        : integer := 30;  --ChanEnableReg:SetPhyReset
  constant kSetPhyReset           : integer := 30;  --ChanEnableReg:SetPhyReset
  constant kPhyResetActiveSize       : integer :=  1;  --ChanEnableReg:PhyResetActive
  constant kPhyResetActiveMsb        : integer := 30;  --ChanEnableReg:PhyResetActive
  constant kPhyResetActive           : integer := 30;  --ChanEnableReg:PhyResetActive
  constant kClrPhyResetSize       : integer :=  1;  --ChanEnableReg:ClrPhyReset
  constant kClrPhyResetMsb        : integer := 31;  --ChanEnableReg:ClrPhyReset
  constant kClrPhyReset           : integer := 31;  --ChanEnableReg:ClrPhyReset
  function kChanEnableRegRec return XReg2_t; -- Register Record function

  -- HsModeCtrlReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kHsModeCtrlReg : integer := 16#4#; -- Register Offset
  constant kHsModeCtrlRegSize: integer := 32;  -- register width in bits
  constant kHsModeCtrlRegMask : std_logic_vector(31 downto 0) := X"0000ffff";
  constant kForceTxHsModeSize       : integer := 8;  --HsModeCtrlReg:ForceTxHsMode
  constant kForceTxHsModeMsb        : integer := 7;  --HsModeCtrlReg:ForceTxHsMode
  constant kForceTxHsMode           : integer := 0;  --HsModeCtrlReg:ForceTxHsMode
  constant kTxHsModeForcedSize       : integer := 8;  --HsModeCtrlReg:TxHsModeForced
  constant kTxHsModeForcedMsb        : integer := 7;  --HsModeCtrlReg:TxHsModeForced
  constant kTxHsModeForced           : integer := 0;  --HsModeCtrlReg:TxHsModeForced
  constant kUnforceTxHsModeSize       : integer :=  8;  --HsModeCtrlReg:UnforceTxHsMode
  constant kUnforceTxHsModeMsb        : integer := 15;  --HsModeCtrlReg:UnforceTxHsMode
  constant kUnforceTxHsMode           : integer :=  8;  --HsModeCtrlReg:UnforceTxHsMode
  function kHsModeCtrlRegRec return XReg2_t; -- Register Record function

  -- StopModeCtrlReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kStopModeCtrlReg : integer := 16#8#; -- Register Offset
  constant kStopModeCtrlRegSize: integer := 32;  -- register width in bits
  constant kStopModeCtrlRegMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kForceTxStopModeSize       : integer := 8;  --StopModeCtrlReg:ForceTxStopMode
  constant kForceTxStopModeMsb        : integer := 7;  --StopModeCtrlReg:ForceTxStopMode
  constant kForceTxStopMode           : integer := 0;  --StopModeCtrlReg:ForceTxStopMode
  constant kForcingStopModeSize       : integer := 8;  --StopModeCtrlReg:ForcingStopMode
  constant kForcingStopModeMsb        : integer := 7;  --StopModeCtrlReg:ForcingStopMode
  constant kForcingStopMode           : integer := 0;  --StopModeCtrlReg:ForcingStopMode
  constant kUnforceTxStopModeSize       : integer :=  8;  --StopModeCtrlReg:UnforceTxStopMode
  constant kUnforceTxStopModeMsb        : integer := 15;  --StopModeCtrlReg:UnforceTxStopMode
  constant kUnforceTxStopMode           : integer :=  8;  --StopModeCtrlReg:UnforceTxStopMode
  constant kForceRxModeSize       : integer :=  8;  --StopModeCtrlReg:ForceRxMode
  constant kForceRxModeMsb        : integer := 23;  --StopModeCtrlReg:ForceRxMode
  constant kForceRxMode           : integer := 16;  --StopModeCtrlReg:ForceRxMode
  constant kForcingRxModeSize       : integer :=  8;  --StopModeCtrlReg:ForcingRxMode
  constant kForcingRxModeMsb        : integer := 23;  --StopModeCtrlReg:ForcingRxMode
  constant kForcingRxMode           : integer := 16;  --StopModeCtrlReg:ForcingRxMode
  constant kUnforceRxModeSize       : integer :=  8;  --StopModeCtrlReg:UnforceRxMode
  constant kUnforceRxModeMsb        : integer := 31;  --StopModeCtrlReg:UnforceRxMode
  constant kUnforceRxMode           : integer := 24;  --StopModeCtrlReg:UnforceRxMode
  function kStopModeCtrlRegRec return XReg2_t; -- Register Record function

  -- ChanStatus1Reg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kChanStatus1Reg : integer := 16#C#; -- Register Offset
  constant kChanStatus1RegSize: integer := 32;  -- register width in bits
  constant kChanStatus1RegMask : std_logic_vector(31 downto 0) := X"0000ffff";
  constant kInitDoneSize       : integer := 8;  --ChanStatus1Reg:InitDone
  constant kInitDoneMsb        : integer := 7;  --ChanStatus1Reg:InitDone
  constant kInitDone           : integer := 0;  --ChanStatus1Reg:InitDone
  constant kStopStateSize       : integer :=  8;  --ChanStatus1Reg:StopState
  constant kStopStateMsb        : integer := 15;  --ChanStatus1Reg:StopState
  constant kStopState           : integer :=  8;  --ChanStatus1Reg:StopState
  function kChanStatus1RegRec return XReg2_t; -- Register Record function

  -- ChanStatus2Reg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kChanStatus2Reg : integer := 16#10#; -- Register Offset
  constant kChanStatus2RegSize: integer := 32;  -- register width in bits
  constant kChanStatus2RegMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kUlpsActiveSize       : integer := 8;  --ChanStatus2Reg:UlpsActive
  constant kUlpsActiveMsb        : integer := 7;  --ChanStatus2Reg:UlpsActive
  constant kUlpsActive           : integer := 0;  --ChanStatus2Reg:UlpsActive
  constant kRxClkActiveSize       : integer :=  8;  --ChanStatus2Reg:RxClkActive
  constant kRxClkActiveMsb        : integer := 15;  --ChanStatus2Reg:RxClkActive
  constant kRxClkActive           : integer :=  8;  --ChanStatus2Reg:RxClkActive
  constant kRxUlpsClkSize       : integer :=  8;  --ChanStatus2Reg:RxUlpsClk
  constant kRxUlpsClkMsb        : integer := 23;  --ChanStatus2Reg:RxUlpsClk
  constant kRxUlpsClk           : integer := 16;  --ChanStatus2Reg:RxUlpsClk
  constant kChanIsRxSize       : integer :=  8;  --ChanStatus2Reg:ChanIsRx
  constant kChanIsRxMsb        : integer := 31;  --ChanStatus2Reg:ChanIsRx
  constant kChanIsRx           : integer := 24;  --ChanStatus2Reg:ChanIsRx
  function kChanStatus2RegRec return XReg2_t; -- Register Record function

  -- PhyIfcSignatureReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kPhyIfcSignatureReg : integer := 16#14#; -- Register Offset
  constant kPhyIfcSignatureRegSize: integer := 32;  -- register width in bits
  constant kPhyIfcSignatureRegMask : std_logic_vector(31 downto 0) := X"ffffffff";
  constant kPhyIfcSignatureSize       : integer := 32;  --PhyIfcSignatureReg:PhyIfcSignature
  constant kPhyIfcSignatureMsb        : integer := 31;  --PhyIfcSignatureReg:PhyIfcSignature
  constant kPhyIfcSignature           : integer :=  0;  --PhyIfcSignatureReg:PhyIfcSignature
  function kPhyIfcSignatureRegRec return XReg2_t; -- Register Record function

  -- ActiveLaneCount Register (from mipi_csi2_core_raw_stripped.xml)
  constant kActiveLaneCount : integer := 16#34#; -- Register Offset
  constant kActiveLaneCountSize: integer := 32;  -- register width in bits
  constant kActiveLaneCountMask : std_logic_vector(31 downto 0) := X"77777777";
  constant kActiveLaneCountCh0Size       : integer := 3;  --ActiveLaneCount:ActiveLaneCountCh0
  constant kActiveLaneCountCh0Msb        : integer := 2;  --ActiveLaneCount:ActiveLaneCountCh0
  constant kActiveLaneCountCh0           : integer := 0;  --ActiveLaneCount:ActiveLaneCountCh0
  constant kActiveLaneCountCh1Size       : integer := 3;  --ActiveLaneCount:ActiveLaneCountCh1
  constant kActiveLaneCountCh1Msb        : integer := 6;  --ActiveLaneCount:ActiveLaneCountCh1
  constant kActiveLaneCountCh1           : integer := 4;  --ActiveLaneCount:ActiveLaneCountCh1
  constant kActiveLaneCountCh2Size       : integer :=  3;  --ActiveLaneCount:ActiveLaneCountCh2
  constant kActiveLaneCountCh2Msb        : integer := 10;  --ActiveLaneCount:ActiveLaneCountCh2
  constant kActiveLaneCountCh2           : integer :=  8;  --ActiveLaneCount:ActiveLaneCountCh2
  constant kActiveLaneCountCh3Size       : integer :=  3;  --ActiveLaneCount:ActiveLaneCountCh3
  constant kActiveLaneCountCh3Msb        : integer := 14;  --ActiveLaneCount:ActiveLaneCountCh3
  constant kActiveLaneCountCh3           : integer := 12;  --ActiveLaneCount:ActiveLaneCountCh3
  constant kActiveLaneCountCh4Size       : integer :=  3;  --ActiveLaneCount:ActiveLaneCountCh4
  constant kActiveLaneCountCh4Msb        : integer := 18;  --ActiveLaneCount:ActiveLaneCountCh4
  constant kActiveLaneCountCh4           : integer := 16;  --ActiveLaneCount:ActiveLaneCountCh4
  constant kActiveLaneCountCh5Size       : integer :=  3;  --ActiveLaneCount:ActiveLaneCountCh5
  constant kActiveLaneCountCh5Msb        : integer := 22;  --ActiveLaneCount:ActiveLaneCountCh5
  constant kActiveLaneCountCh5           : integer := 20;  --ActiveLaneCount:ActiveLaneCountCh5
  constant kActiveLaneCountCh6Size       : integer :=  3;  --ActiveLaneCount:ActiveLaneCountCh6
  constant kActiveLaneCountCh6Msb        : integer := 26;  --ActiveLaneCount:ActiveLaneCountCh6
  constant kActiveLaneCountCh6           : integer := 24;  --ActiveLaneCount:ActiveLaneCountCh6
  constant kActiveLaneCountCh7Size       : integer :=  3;  --ActiveLaneCount:ActiveLaneCountCh7
  constant kActiveLaneCountCh7Msb        : integer := 30;  --ActiveLaneCount:ActiveLaneCountCh7
  constant kActiveLaneCountCh7           : integer := 28;  --ActiveLaneCount:ActiveLaneCountCh7
  function kActiveLaneCountRec return XReg2_t; -- Register Record function

--===============================================================================
-- Register Group Timing
--===============================================================================

  -- TxStopStateDwellReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kTxStopStateDwellReg : integer := 16#2C#; -- Register Offset
  constant kTxStopStateDwellRegSize: integer := 32;  -- register width in bits
  constant kTxStopStateDwellRegMask : std_logic_vector(31 downto 0) := X"000003ff";
  constant kTxStopStateDwellSize       : integer := 10;  --TxStopStateDwellReg:TxStopStateDwell
  constant kTxStopStateDwellMsb        : integer :=  9;  --TxStopStateDwellReg:TxStopStateDwell
  constant kTxStopStateDwell           : integer :=  0;  --TxStopStateDwellReg:TxStopStateDwell
  function kTxStopStateDwellRegRec return XReg2_t; -- Register Record function

  -- TxHighSpeedDwellReg Register (from mipi_csi2_core_raw_stripped.xml)
  constant kTxHighSpeedDwellReg : integer := 16#30#; -- Register Offset
  constant kTxHighSpeedDwellRegSize: integer := 32;  -- register width in bits
  constant kTxHighSpeedDwellRegMask : std_logic_vector(31 downto 0) := X"000003ff";
  constant kTxHighSpeedDwellSize       : integer := 10;  --TxHighSpeedDwellReg:TxHighSpeedDwell
  constant kTxHighSpeedDwellMsb        : integer :=  9;  --TxHighSpeedDwellReg:TxHighSpeedDwell
  constant kTxHighSpeedDwell           : integer :=  0;  --TxHighSpeedDwellReg:TxHighSpeedDwell
  function kTxHighSpeedDwellRegRec return XReg2_t; -- Register Record function

end package;

package body PkgDPhyIfcRegmap is

  -- Return the record of register kPacketHeaderForGenReg
  function kPacketHeaderForGenRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"18");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"ffffffff");
    Rec.rmask := XRegResize(X"ffffffff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kHeaderDataType) := kHeaderDataTypeMsb;
    Rec.msblookupw(kHeaderVC10) := kHeaderVC10Msb;
    Rec.msblookupw(kHeaderData) := kHeaderDataMsb;
    Rec.msblookupw(kHeaderECC) := kHeaderECCMsb;
    Rec.msblookupw(kHeaderVC32) := kHeaderVC32Msb;
    Rec.msblookupr(kHeaderDataType) := kHeaderDataTypeMsb;
    Rec.msblookupr(kHeaderVC10) := kHeaderVC10Msb;
    Rec.msblookupr(kHeaderData) := kHeaderDataMsb;
    Rec.msblookupr(kHeaderECC) := kHeaderECCMsb;
    Rec.msblookupr(kHeaderVC32) := kHeaderVC32Msb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("PacketHeaderForGenReg");
    --synopsys translate_on
    return Rec;
  end function kPacketHeaderForGenRegRec;

  -- Return the record of register kPacketFillerForGenReg
  function kPacketFillerForGenRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"1C");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"000000ff");
    Rec.rmask := XRegResize(X"000000ff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kFillerCount) := kFillerCountMsb;
    Rec.msblookupr(kFillerCount) := kFillerCountMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("PacketFillerForGenReg");
    --synopsys translate_on
    return Rec;
  end function kPacketFillerForGenRegRec;

  -- Return the record of register kGenPacketReg
  function kGenPacketRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"20");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"000000ff");
    Rec.rmask := XRegResize(X"000000ff");
    Rec.strobemask := XRegResize(X"000000ff");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kGenerate) := kGenerateMsb;
    Rec.msblookupr(kGenerating) := kGeneratingMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("GenPacketReg");
    --synopsys translate_on
    return Rec;
  end function kGenPacketRegRec;

  -- Return the record of register kTxChan0DebugReg0
  function kTxChan0DebugReg0Rec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"24");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := false;
    Rec.wmask := XRegResize(X"ffdffcff");
    Rec.rmask := XRegResize(X"ffdffcff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kTxFifoEmptyCount) := kTxFifoEmptyCountMsb;
    Rec.msblookupw(kTxFifoFullCount) := kTxFifoFullCountMsb;
    Rec.msblookupw(kTxDlState) := kTxDlStateMsb;
    Rec.msblookupw(kTxLaneHasSpace) := kTxLaneHasSpaceMsb;
    Rec.msblookupw(kTxLaneHasData) := kTxLaneHasDataMsb;
    Rec.msblookupr(kTxFifoEmptyCount) := kTxFifoEmptyCountMsb;
    Rec.msblookupr(kTxFifoFullCount) := kTxFifoFullCountMsb;
    Rec.msblookupr(kTxDlState) := kTxDlStateMsb;
    Rec.msblookupr(kTxLaneHasSpace) := kTxLaneHasSpaceMsb;
    Rec.msblookupr(kTxLaneHasData) := kTxLaneHasDataMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("TxChan0DebugReg0");
    --synopsys translate_on
    return Rec;
  end function kTxChan0DebugReg0Rec;

  -- Return the record of register kTxChan0DebugReg1
  function kTxChan0DebugReg1Rec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"28");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := false;
    Rec.wmask := XRegResize(X"ffff3fff");
    Rec.rmask := XRegResize(X"ffff3fff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kTxPacketCount) := kTxPacketCountMsb;
    Rec.msblookupw(kTxWordCount) := kTxWordCountMsb;
    Rec.msblookupr(kTxPacketCount) := kTxPacketCountMsb;
    Rec.msblookupr(kTxWordCount) := kTxWordCountMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("TxChan0DebugReg1");
    --synopsys translate_on
    return Rec;
  end function kTxChan0DebugReg1Rec;

  -- Return the record of register kChanEnableReg
  function kChanEnableRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"0");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"c000ffff");
    Rec.rmask := XRegResize(X"400000ff");
    Rec.strobemask := XRegResize(X"c000ffff");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kChanEnable) := kChanEnableMsb;
    Rec.msblookupw(kChanDisable) := kChanDisableMsb;
    Rec.msblookupr(kChanEnabled) := kChanEnabledMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ChanEnableReg");
    --synopsys translate_on
    return Rec;
  end function kChanEnableRegRec;

  -- Return the record of register kHsModeCtrlReg
  function kHsModeCtrlRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"4");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"0000ffff");
    Rec.rmask := XRegResize(X"000000ff");
    Rec.strobemask := XRegResize(X"0000ffff");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kForceTxHsMode) := kForceTxHsModeMsb;
    Rec.msblookupw(kUnforceTxHsMode) := kUnforceTxHsModeMsb;
    Rec.msblookupr(kTxHsModeForced) := kTxHsModeForcedMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("HsModeCtrlReg");
    --synopsys translate_on
    return Rec;
  end function kHsModeCtrlRegRec;

  -- Return the record of register kStopModeCtrlReg
  function kStopModeCtrlRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"8");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"ffffffff");
    Rec.rmask := XRegResize(X"00ff00ff");
    Rec.strobemask := XRegResize(X"ffffffff");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kForceTxStopMode) := kForceTxStopModeMsb;
    Rec.msblookupw(kUnforceTxStopMode) := kUnforceTxStopModeMsb;
    Rec.msblookupw(kForceRxMode) := kForceRxModeMsb;
    Rec.msblookupw(kUnforceRxMode) := kUnforceRxModeMsb;
    Rec.msblookupr(kForcingStopMode) := kForcingStopModeMsb;
    Rec.msblookupr(kForcingRxMode) := kForcingRxModeMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("StopModeCtrlReg");
    --synopsys translate_on
    return Rec;
  end function kStopModeCtrlRegRec;

  -- Return the record of register kChanStatus1Reg
  function kChanStatus1RegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"C");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := false;
    Rec.wmask := XRegResize(X"0000ffff");
    Rec.rmask := XRegResize(X"0000ffff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kInitDone) := kInitDoneMsb;
    Rec.msblookupw(kStopState) := kStopStateMsb;
    Rec.msblookupr(kInitDone) := kInitDoneMsb;
    Rec.msblookupr(kStopState) := kStopStateMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ChanStatus1Reg");
    --synopsys translate_on
    return Rec;
  end function kChanStatus1RegRec;

  -- Return the record of register kChanStatus2Reg
  function kChanStatus2RegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"10");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := false;
    Rec.wmask := XRegResize(X"ffffffff");
    Rec.rmask := XRegResize(X"ffffffff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kUlpsActive) := kUlpsActiveMsb;
    Rec.msblookupw(kRxClkActive) := kRxClkActiveMsb;
    Rec.msblookupw(kRxUlpsClk) := kRxUlpsClkMsb;
    Rec.msblookupw(kChanIsRx) := kChanIsRxMsb;
    Rec.msblookupr(kUlpsActive) := kUlpsActiveMsb;
    Rec.msblookupr(kRxClkActive) := kRxClkActiveMsb;
    Rec.msblookupr(kRxUlpsClk) := kRxUlpsClkMsb;
    Rec.msblookupr(kChanIsRx) := kChanIsRxMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ChanStatus2Reg");
    --synopsys translate_on
    return Rec;
  end function kChanStatus2RegRec;

  -- Return the record of register kPhyIfcSignatureReg
  function kPhyIfcSignatureRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"14");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := false;
    Rec.wmask := XRegResize(X"ffffffff");
    Rec.rmask := XRegResize(X"ffffffff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kPhyIfcSignature) := kPhyIfcSignatureMsb;
    Rec.msblookupr(kPhyIfcSignature) := kPhyIfcSignatureMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("PhyIfcSignatureReg");
    --synopsys translate_on
    return Rec;
  end function kPhyIfcSignatureRegRec;

  -- Return the record of register kActiveLaneCount
  function kActiveLaneCountRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"34");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"77777777");
    Rec.rmask := XRegResize(X"77777777");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kActiveLaneCountCh0) := kActiveLaneCountCh0Msb;
    Rec.msblookupw(kActiveLaneCountCh1) := kActiveLaneCountCh1Msb;
    Rec.msblookupw(kActiveLaneCountCh2) := kActiveLaneCountCh2Msb;
    Rec.msblookupw(kActiveLaneCountCh3) := kActiveLaneCountCh3Msb;
    Rec.msblookupw(kActiveLaneCountCh4) := kActiveLaneCountCh4Msb;
    Rec.msblookupw(kActiveLaneCountCh5) := kActiveLaneCountCh5Msb;
    Rec.msblookupw(kActiveLaneCountCh6) := kActiveLaneCountCh6Msb;
    Rec.msblookupw(kActiveLaneCountCh7) := kActiveLaneCountCh7Msb;
    Rec.msblookupr(kActiveLaneCountCh0) := kActiveLaneCountCh0Msb;
    Rec.msblookupr(kActiveLaneCountCh1) := kActiveLaneCountCh1Msb;
    Rec.msblookupr(kActiveLaneCountCh2) := kActiveLaneCountCh2Msb;
    Rec.msblookupr(kActiveLaneCountCh3) := kActiveLaneCountCh3Msb;
    Rec.msblookupr(kActiveLaneCountCh4) := kActiveLaneCountCh4Msb;
    Rec.msblookupr(kActiveLaneCountCh5) := kActiveLaneCountCh5Msb;
    Rec.msblookupr(kActiveLaneCountCh6) := kActiveLaneCountCh6Msb;
    Rec.msblookupr(kActiveLaneCountCh7) := kActiveLaneCountCh7Msb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ActiveLaneCount");
    --synopsys translate_on
    return Rec;
  end function kActiveLaneCountRec;

  -- Return the record of register kTxStopStateDwellReg
  function kTxStopStateDwellRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"2C");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"000003ff");
    Rec.rmask := XRegResize(X"000003ff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kTxStopStateDwell) := kTxStopStateDwellMsb;
    Rec.msblookupr(kTxStopStateDwell) := kTxStopStateDwellMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("TxStopStateDwellReg");
    --synopsys translate_on
    return Rec;
  end function kTxStopStateDwellRegRec;

  -- Return the record of register kTxHighSpeedDwellReg
  function kTxHighSpeedDwellRegRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"30");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"000003ff");
    Rec.rmask := XRegResize(X"000003ff");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.msblookupw(kTxHighSpeedDwell) := kTxHighSpeedDwellMsb;
    Rec.msblookupr(kTxHighSpeedDwell) := kTxHighSpeedDwellMsb;
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("TxHighSpeedDwellReg");
    --synopsys translate_on
    return Rec;
  end function kTxHighSpeedDwellRegRec;

end package body;
