-------------------------------------------------------------------------------
--
-- File: PkgTimingEngine.vhd
-- Author: Autogenerated by XmlParse
-- Original Project: --
-- Date: --
--
-------------------------------------------------------------------------------
-- (c) 2022 Copyright National Instruments Corporation
-- All Rights Reserved
-- National Instruments Internal Information
-------------------------------------------------------------------------------
--
-- Purpose:
--   The constants in this file are autogenerated by XmlParse and should
-- be used by testbench code to access specific register fields.
--
-------------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;
library work;
  use work.PkgXReg.all;
  --synopsys translate_off
  use work.PkgNiSim.all;
  --synopsys translate_on

package PkgTimingEngine is

--===============================================================================
-- A numerically ordered list of registers and their VHDL source files
--===============================================================================

  -- MmcmControl            : 0x0 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllOut.vhd)
  -- PllControl             : 0x4 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  -- MmcmStatus             : 0x8 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  -- PllStatus              : 0xC (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  -- ClkInSelection         : 0x10 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  -- RxClkInSelection       : 0x14 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd)
  -- RxClkInSelectionBank45 : 0x18 (RegmapTop_raw.xml, TimingEngineAllIn.vhd)
  -- RxClkInSelectionBank46 : 0x1C (RegmapTop_raw.xml, TimingEngineAllIn.vhd)
  -- ClockControl           : 0x20 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  -- ResetClockSyncLogic    : 0x28 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllOut.vhd)
  -- ClkStatus              : 0x30 (RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)

--===============================================================================
-- RegTypes
--===============================================================================

--===============================================================================
-- Register Group ClockEnables
--===============================================================================

  -- ClockControl Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  constant kClockControl : integer := 16#20#; -- Register Offset
  constant kClockControlSize: integer := 32;  -- register width in bits
  constant kClockControlMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetClockGateSize       : integer := 1;  --ClockControl:SetClockGate
  constant kSetClockGateMsb        : integer := 0;  --ClockControl:SetClockGate
  constant kSetClockGate           : integer := 0;  --ClockControl:SetClockGate
  constant kClearClockGateSize       : integer := 1;  --ClockControl:ClearClockGate
  constant kClearClockGateMsb        : integer := 1;  --ClockControl:ClearClockGate
  constant kClearClockGate           : integer := 1;  --ClockControl:ClearClockGate
  function kClockControlRec return XReg2_t; -- Register Record function

  -- ResetClockSyncLogic Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllOut.vhd)
  constant kResetClockSyncLogic : integer := 16#28#; -- Register Offset
  constant kResetClockSyncLogicSize: integer := 32;  -- register width in bits
  constant kResetClockSyncLogicMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetClockSyncLogicResetSize       : integer := 1;  --ResetClockSyncLogic:SetClockSyncLogicReset
  constant kSetClockSyncLogicResetMsb        : integer := 0;  --ResetClockSyncLogic:SetClockSyncLogicReset
  constant kSetClockSyncLogicReset           : integer := 0;  --ResetClockSyncLogic:SetClockSyncLogicReset
  constant kClearClockSyncLogicResetSize       : integer := 1;  --ResetClockSyncLogic:ClearClockSyncLogicReset
  constant kClearClockSyncLogicResetMsb        : integer := 1;  --ResetClockSyncLogic:ClearClockSyncLogicReset
  constant kClearClockSyncLogicReset           : integer := 1;  --ResetClockSyncLogic:ClearClockSyncLogicReset
  function kResetClockSyncLogicRec return XReg2_t; -- Register Record function

  -- ClkStatus Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  constant kClkStatus : integer := 16#30#; -- Register Offset
  constant kClkStatusSize: integer := 32;  -- register width in bits
  constant kClkStatusMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kLvClockEnableSize       : integer := 1;  --ClkStatus:LvClockEnable
  constant kLvClockEnableMsb        : integer := 0;  --ClkStatus:LvClockEnable
  constant kLvClockEnable           : integer := 0;  --ClkStatus:LvClockEnable
  constant kIdelayCtrlReadySize       : integer := 1;  --ClkStatus:IdelayCtrlReady
  constant kIdelayCtrlReadyMsb        : integer := 1;  --ClkStatus:IdelayCtrlReady
  constant kIdelayCtrlReady           : integer := 1;  --ClkStatus:IdelayCtrlReady
  function kClkStatusRec return XReg2_t; -- Register Record function

--===============================================================================
-- Register Group MMCM
--===============================================================================

  -- MmcmControl Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllOut.vhd)
  constant kMmcmControl : integer := 16#0#; -- Register Offset
  constant kMmcmControlSize: integer := 32;  -- register width in bits
  constant kMmcmControlMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetMmcmResetSize       : integer := 1;  --MmcmControl:SetMmcmReset
  constant kSetMmcmResetMsb        : integer := 0;  --MmcmControl:SetMmcmReset
  constant kSetMmcmReset           : integer := 0;  --MmcmControl:SetMmcmReset
  constant kClearMmcmResetSize       : integer := 1;  --MmcmControl:ClearMmcmReset
  constant kClearMmcmResetMsb        : integer := 1;  --MmcmControl:ClearMmcmReset
  constant kClearMmcmReset           : integer := 1;  --MmcmControl:ClearMmcmReset
  function kMmcmControlRec return XReg2_t; -- Register Record function

  -- PllControl Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  constant kPllControl : integer := 16#4#; -- Register Offset
  constant kPllControlSize: integer := 32;  -- register width in bits
  constant kPllControlMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetPllResetSize       : integer := 1;  --PllControl:SetPllReset
  constant kSetPllResetMsb        : integer := 0;  --PllControl:SetPllReset
  constant kSetPllReset           : integer := 0;  --PllControl:SetPllReset
  constant kClearPllResetSize       : integer := 1;  --PllControl:ClearPllReset
  constant kClearPllResetMsb        : integer := 1;  --PllControl:ClearPllReset
  constant kClearPllReset           : integer := 1;  --PllControl:ClearPllReset
  function kPllControlRec return XReg2_t; -- Register Record function

  -- MmcmStatus Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  constant kMmcmStatus : integer := 16#8#; -- Register Offset
  constant kMmcmStatusSize: integer := 32;  -- register width in bits
  constant kMmcmStatusMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kMmcmLockedSize       : integer := 1;  --MmcmStatus:MmcmLocked
  constant kMmcmLockedMsb        : integer := 0;  --MmcmStatus:MmcmLocked
  constant kMmcmLocked           : integer := 0;  --MmcmStatus:MmcmLocked
  constant kMmcmUnlockedStickySize       : integer := 1;  --MmcmStatus:MmcmUnlockedSticky
  constant kMmcmUnlockedStickyMsb        : integer := 1;  --MmcmStatus:MmcmUnlockedSticky
  constant kMmcmUnlockedSticky           : integer := 1;  --MmcmStatus:MmcmUnlockedSticky
  function kMmcmStatusRec return XReg2_t; -- Register Record function

  -- PllStatus Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  constant kPllStatus : integer := 16#C#; -- Register Offset
  constant kPllStatusSize: integer := 32;  -- register width in bits
  constant kPllStatusMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kPllLockedSize       : integer := 1;  --PllStatus:PllLocked
  constant kPllLockedMsb        : integer := 0;  --PllStatus:PllLocked
  constant kPllLocked           : integer := 0;  --PllStatus:PllLocked
  constant kPllUnlockedStickySize       : integer := 1;  --PllStatus:PllUnlockedSticky
  constant kPllUnlockedStickyMsb        : integer := 1;  --PllStatus:PllUnlockedSticky
  constant kPllUnlockedSticky           : integer := 1;  --PllStatus:PllUnlockedSticky
  function kPllStatusRec return XReg2_t; -- Register Record function

  -- ClkInSelection Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineAllOut.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd, TimingEngineBasicAllOut.vhd)
  constant kClkInSelection : integer := 16#10#; -- Register Offset
  constant kClkInSelectionSize: integer := 32;  -- register width in bits
  constant kClkInSelectionMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetClkInSelectionSize       : integer := 1;  --ClkInSelection:SetClkInSelection
  constant kSetClkInSelectionMsb        : integer := 0;  --ClkInSelection:SetClkInSelection
  constant kSetClkInSelection           : integer := 0;  --ClkInSelection:SetClkInSelection
  constant kClearClkInSelectionSize       : integer := 1;  --ClkInSelection:ClearClkInSelection
  constant kClearClkInSelectionMsb        : integer := 1;  --ClkInSelection:ClearClkInSelection
  constant kClearClkInSelection           : integer := 1;  --ClkInSelection:ClearClkInSelection
  function kClkInSelectionRec return XReg2_t; -- Register Record function

  -- RxClkInSelection Register (from RegmapTop_raw.xml, TimingEngine.vhd, TimingEngineAllIn.vhd, TimingEngineBasic.vhd, TimingEngineBasicAllIn.vhd)
  constant kRxClkInSelection : integer := 16#14#; -- Register Offset
  constant kRxClkInSelectionSize: integer := 32;  -- register width in bits
  constant kRxClkInSelectionMask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetRxClkInSelectionSize       : integer := 1;  --RxClkInSelection:SetRxClkInSelection
  constant kSetRxClkInSelectionMsb        : integer := 0;  --RxClkInSelection:SetRxClkInSelection
  constant kSetRxClkInSelection           : integer := 0;  --RxClkInSelection:SetRxClkInSelection
  constant kClearRxClkInSelectionSize       : integer := 1;  --RxClkInSelection:ClearRxClkInSelection
  constant kClearRxClkInSelectionMsb        : integer := 1;  --RxClkInSelection:ClearRxClkInSelection
  constant kClearRxClkInSelection           : integer := 1;  --RxClkInSelection:ClearRxClkInSelection
  function kRxClkInSelectionRec return XReg2_t; -- Register Record function

  -- RxClkInSelectionBank45 Register (from RegmapTop_raw.xml, TimingEngineAllIn.vhd)
  constant kRxClkInSelectionBank45 : integer := 16#18#; -- Register Offset
  constant kRxClkInSelectionBank45Size: integer := 32;  -- register width in bits
  constant kRxClkInSelectionBank45Mask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetRxClkInSelection1Size       : integer := 1;  --RxClkInSelectionBank45:SetRxClkInSelection1
  constant kSetRxClkInSelection1Msb        : integer := 0;  --RxClkInSelectionBank45:SetRxClkInSelection1
  constant kSetRxClkInSelection1           : integer := 0;  --RxClkInSelectionBank45:SetRxClkInSelection1
  constant kClearRxClkInSelection1Size       : integer := 1;  --RxClkInSelectionBank45:ClearRxClkInSelection1
  constant kClearRxClkInSelection1Msb        : integer := 1;  --RxClkInSelectionBank45:ClearRxClkInSelection1
  constant kClearRxClkInSelection1           : integer := 1;  --RxClkInSelectionBank45:ClearRxClkInSelection1
  function kRxClkInSelectionBank45Rec return XReg2_t; -- Register Record function

  -- RxClkInSelectionBank46 Register (from RegmapTop_raw.xml, TimingEngineAllIn.vhd)
  constant kRxClkInSelectionBank46 : integer := 16#1C#; -- Register Offset
  constant kRxClkInSelectionBank46Size: integer := 32;  -- register width in bits
  constant kRxClkInSelectionBank46Mask : std_logic_vector(31 downto 0) := X"00000003";
  constant kSetRxClkInSelection2Size       : integer := 1;  --RxClkInSelectionBank46:SetRxClkInSelection2
  constant kSetRxClkInSelection2Msb        : integer := 0;  --RxClkInSelectionBank46:SetRxClkInSelection2
  constant kSetRxClkInSelection2           : integer := 0;  --RxClkInSelectionBank46:SetRxClkInSelection2
  constant kClearRxClkInSelection2Size       : integer := 1;  --RxClkInSelectionBank46:ClearRxClkInSelection2
  constant kClearRxClkInSelection2Msb        : integer := 1;  --RxClkInSelectionBank46:ClearRxClkInSelection2
  constant kClearRxClkInSelection2           : integer := 1;  --RxClkInSelectionBank46:ClearRxClkInSelection2
  function kRxClkInSelectionBank46Rec return XReg2_t; -- Register Record function

end package;

package body PkgTimingEngine is

  -- Return the record of register kClockControl
  function kClockControlRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"20");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ClockControl");
    --synopsys translate_on
    return Rec;
  end function kClockControlRec;

  -- Return the record of register kResetClockSyncLogic
  function kResetClockSyncLogicRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"28");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ResetClockSyncLogic");
    --synopsys translate_on
    return Rec;
  end function kResetClockSyncLogicRec;

  -- Return the record of register kClkStatus
  function kClkStatusRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"30");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := false;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000003");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ClkStatus");
    --synopsys translate_on
    return Rec;
  end function kClkStatusRec;

  -- Return the record of register kMmcmControl
  function kMmcmControlRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"0");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("MmcmControl");
    --synopsys translate_on
    return Rec;
  end function kMmcmControlRec;

  -- Return the record of register kPllControl
  function kPllControlRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"4");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("PllControl");
    --synopsys translate_on
    return Rec;
  end function kPllControlRec;

  -- Return the record of register kMmcmStatus
  function kMmcmStatusRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"8");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000002");
    Rec.rmask := XRegResize(X"00000003");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000002");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("MmcmStatus");
    --synopsys translate_on
    return Rec;
  end function kMmcmStatusRec;

  -- Return the record of register kPllStatus
  function kPllStatusRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"C");
    Rec.size := 32;
    Rec.readable := true;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000002");
    Rec.rmask := XRegResize(X"00000003");
    Rec.strobemask := XRegResize(X"00000000");
    Rec.clearablemask := XRegResize(X"00000002");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("PllStatus");
    --synopsys translate_on
    return Rec;
  end function kPllStatusRec;

  -- Return the record of register kClkInSelection
  function kClkInSelectionRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"10");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("ClkInSelection");
    --synopsys translate_on
    return Rec;
  end function kClkInSelectionRec;

  -- Return the record of register kRxClkInSelection
  function kRxClkInSelectionRec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"14");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("RxClkInSelection");
    --synopsys translate_on
    return Rec;
  end function kRxClkInSelectionRec;

  -- Return the record of register kRxClkInSelectionBank45
  function kRxClkInSelectionBank45Rec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"18");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("RxClkInSelectionBank45");
    --synopsys translate_on
    return Rec;
  end function kRxClkInSelectionBank45Rec;

  -- Return the record of register kRxClkInSelectionBank46
  function kRxClkInSelectionBank46Rec return XReg2_t is
    variable Rec : XReg2_t;
  begin
    Rec := kXRegDefault;
    Rec.version := 1;
    Rec.offset := XAddrResize(X"1C");
    Rec.size := 32;
    Rec.readable := false;
    Rec.writable := true;
    Rec.wmask := XRegResize(X"00000003");
    Rec.rmask := XRegResize(X"00000000");
    Rec.strobemask := XRegResize(X"00000003");
    Rec.clearablemask := XRegResize(X"00000000");
    -- no initial values specified
    -- Single-bit bitfields are not listed here because the default for msblookup* is msb=lsb.
    Rec.isreg := true;
    --synopsys translate_off
    Rec.name := rs("RxClkInSelectionBank46");
    --synopsys translate_on
    return Rec;
  end function kRxClkInSelectionBank46Rec;

end package body;
